version: '3.9'

services:
  app:
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${NUXT_PORT:-3000}:3000'
    networks:
      - app

networks:
  app:
    driver: bridge
    name: nuxt-app
